# Site settings
title: maloney.ws
person_name: niall-maloney
email: niall@maloney.ws
description: backend dev - c#, docker, k8s
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maloney.ws" # the base hostname & protocol for your site
twitter_username: maloney_ws
github_username:  niall-maloney
linkedin_username: niall-maloney
spotify_username: fozzi_bear

# Build settings
markdown: kramdown
